<div class="main-container about-page">
					<div class="page-content">
						<div class="entry-content">
							<div class="phm_row hasteck_row phm_row-fluid content-about1 parvez_custom_about">
								<div class="row-container">
									<div class="parvez_column parvez_column_container parvez_col-sm-6 parvez_custom_about_2">
										<div class="parvez_wrapper">
											<div class="parvez_text_column parvez_content_element ">
												<div class="parvez_wrapper">
													<p>
														<a href="#">
															<img class="alignnone size-full" src="http://demo.roadthemes.com/saharan_accessories/wp-content/uploads/2014/12/about.jpg" alt="about" width="600" height="708" />
														</a>
													</p>
												</div>
											</div>
										</div>
									</div>
									<div class="parvez_column parvez_column_container parvez_col-sm-6 parvez_custom_about_3">
										<div class="parvez_wrapper">
											<div class="parvez_text_column parvez_content_element ">
												<div class="parvez_wrapper">
													<h4>who’s</h4>
													<h2>saharan</h2>
													<h3>Fashion Design</h3>
													<p>Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>
													<h3>London Address</h3>
													<p>34 Parer Place via Musk Avenue Kelvin Grove, QLD, 4059</p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							
							
						</div>
					</div>
				</div>