<div class="row">
    <div class="span12" 
        <div class="row">
            <div class="span12">
                <div class="slider_off"> </div>
            </div>
        </div>
        <div class="row">       
            <div class="span12">
                <div class="post-497 portfolio type-portfolio status-publish has-post-thumbnail hentry" >
                        <div class="row">
                            <div class="span7">
                                 <video controls preload="auto" src="{{videoDetail.video_link}}" width="100%"></video>'                             
                                <br>
                                <div class="clear"></div>
                            </div>
                            <div class="entry-content span5">
                                <div class="">
                                    <div class="entry-meta ">                                      
                                           <h3>{{videoDetail.title}}</h3>
                                        <ul class="portfolio-meta-list">
                                            <li><strong class="portfolio-meta-key">Lượt xem:</strong><span>{{videoDetail.total_view}}</span>
                                                <br>
                                            </li>
                                            <li><strong class="portfolio-meta-key">Đăng ngày:</strong><span>{{ date("Y-m-d H:i", time(r.create_date)) }}</span>
                                                <br>
                                            </li>
                                            <li><strong class="portfolio-meta-key">Danh mục:</strong><a target="_blank" href="#">{{videoDetail.Menu.name}}</a>
                                                <br>
                                            </li>                                        
                                        </ul>
                                    </div>
                                    <div>
                                        {{videoDetail.description}}
                                    
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="span7">
                                <div class="related-posts">
                                    <h3 class="related-posts_h">Video khác</h3>
                                    <ul class="related-posts_list clearfix">
                                        {% for l in videoList.items %}
                                        <li class="related-posts_item">
                                            <figure class="thumbnail featured-thumbnail">
                                                <a href="/video/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/" title="{{l.title}}">
                                                    <img alt="{{l.title}}" src="{{l.img_url}}">
                                                </a>
                                            </figure>
                                            <a href="/video/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/">{{l.title}}</a>
                                        </li>
                                         {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>         
        </div>
    </div>
</div>
</div>
