<div class="row">
    <div class="span12" >
        <div class="row">
            <div class="span12">
                <div class="slider_off"> </div>
            </div>
        </div>
        <div class="row">
            <div class="span12" >
                <div id="post-203" class="post-203 page type-page status-publish hentry">
                    <div class="row">
                        <div class="span12" >
                            <section class="title-section">
                                <h1 class="title-header">
                                    Videos 
                                </h1>
                                <ul class="breadcrumb breadcrumb__t">
                                    <li><a href="#">Trang chủ</a></li>
                                    <li class="divider"></li>
                                    <li class="active">Videos</li>
                                </ul>
                            </section>
                        </div>
                    </div>
                    <div id="content" class="row">
                        {{ partial('videoList') }}
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>