<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title">Add category</h4>
</div>
<div class="modal-body" style="height: 250px;">
	<div class="col-md-12">
		<div class="col-md-5">List categry</div>
		<div class="col-md-2"></div>		
	</div>
	<div class="col-md-12">
		<select multiple="multiple" class="multi-select" id="list_parent" name="list_parent[]">
			{% for index,item in lstparent %}
			<option value="{{item['cate_id']}}" {{item["selected"]}}>{{item['name']}}</option>
			{% endfor %}
		</select>
	</div>
</div>
<div class="modal-footer">
	<button type="button" data-dismiss="modal" class="btn btn-outline dark">Close</button>
	<button type="button" data-dismiss="modal" class="btn green" onclick="SaveChildCategory()">OK</button>
</div>
<script type="text/javascript">
	$(function(){
		$('#list_parent').multiSelect();
	});

	function SaveChildCategory(){
        var _returnChild  = "";
        $("#ms-list_parent div.ms-selection li").each(function(_index, _val){
            $_this = $(this);
            if($_this.is(":visible")){
                var _textSelected = $_this.children("span").html().trim();
                $("#list_parent option").each(function(_indexs,_select){
                    if( _textSelected != "" && _textSelected == $(_select).text().trim() ){
                        _returnChild += $(_select).val() + "@@";
                    }
                })
            }
        });
        $("#child_list").val(_returnChild);
    }
</script>
