<!-- apps/views/menu/edit.phtml-->
<?php
use Multiple\Backend\Models\Brand as Brand;
use Phalcon\Tag as Tag;
?>
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{base_url}}/cpanel/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{base_url}}/cpanel/{{ControllerName}}">Brand manager</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            {{id > 0 ?"Edit": "Add new" }} Brand
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> Menu
    <small>{{id > 0 ? "Edit" : "Add new" }} Brand</small>
</h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div>
    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light bordered">
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <form action="/cpanel/{{ControllerName}}/{{ActionName}}/{{id >0 ? id :""}}" class="form-horizontal" method="post" >
                {{ hidden_field("brand_id", "value": id) }}
                <div class="form-body">
                    <div class="form-group">
                        <label class="control-label col-md-2">Name
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("name","class":"form-control","data-required":"1" , "value" : not detail is empty  ? detail.name :'') }}
                        </div>
                    </div>
                    {% if id > 0 %}
                    <div class="form-group">
                        <label class="control-label col-md-2">Seo URL
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("seo_url","class":"form-control", "value" : not detail is empty  ? detail.seo_url :'') }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <label class="control-label col-md-2">Sort order</label>
                        <div class="col-md-10">
                            {{ text_field("order_id","class":"form-control" , "value" : not detail is empty  ? detail.order_id :'') }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Logo
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                    {% if not detail is empty %}
                                        {{ image(baseImageURL ~ detail.logo)}}
                                        {{ hidden_field("himage_url", "value": detail.logo) }}
                                    {% endif %}
                                </div>
                                <div>
                                    <span class="btn green btn-file">
                                        <span class="fileinput-new"> Select image </span>
                                        <span class="fileinput-exists"> Change </span>
                                        <input type="file" name="img_url">
                                    </span>
                                    {{link_to("javascript:;", "Remove", "class": "btn red fileinput-exists", "data-dismiss":"fileinput")}}
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Status</label>
                        <div class="col-md-10">
                            <?php
                            // Creating a Select Tag with an empty option
                            echo $this->tag->selectStatic(
                                array(
                                    'status',
                                    array(
                                        '1' => 'Active',
                                        '0' => 'Inactive'
                                    ),
                                    'useEmpty'      => true,
                                    'emptyText'     => 'Please, choose one...',
                                    'emptyValue'    => '',
                                    'class'         => 'form-control',
                                    'value'         => !empty($detail) ? $detail->status : '',
                                )
                            );
                            ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green">Save</button>
                            <button type="button" class="btn default">Cancel</button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- END FORM-->
        </div>
    </div>
    <!-- END VALIDATION STATES-->
</div>
