<div class="row">
    <div class="col-md-5 col-sm-5">
        <div class="dataTables_info" id="sample_editable_1_info" role="status" aria-live="polite">
            Showing {{start}} to {{end}} of {{total_records}} entries
        </div>
    </div>
    <div class="col-md-7 col-sm-7" id="div-paging">
        <div class="dataTables_paginate paging_bootstrap_number">
            <ul class="pagination" style="visibility: visible;">
                <li class="prev {{current <=1 ? "disabled":""}}">
                    <a title="Prev" href="javascript:;" data-pageindex="1">
                        <i class="fa fa-angle-left"></i>
                    </a>
                </li>
                <?php for($i = 0 ; $i < $total_pages; $i++): ?>
                    <li class={{current == i +1 ? "active" :"" }}>
                        <a href="javascript:;" data-pageindex="{{i +1}}">{{i +1 }}</a>
                    </li>
                <?php endfor; ?>
                <li class = "{{current == total_pages or total_records==0 ? " next disabled" :"next" }}">
                    <a title="Next" href="javascript:;" data-pageindex="{{total_pages}}">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

