<!-- apps/views/index/contact.phtml-->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{base_url}}/cpanel/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
           Edit Contact info
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> CONTACT
    <small>Edit contact infomation</small>
</h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->

<div>
    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light bordered">
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <form action="/cpanel/contact" class="form-horizontal" method="post"
                  enctype="multipart/form-data">
                <div class="form-actions top right">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green">Save</button>
                            <button type="button" class="btn default">Cancel</button>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="form-group">
                        <label class="control-label col-md-2">Name
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("name","class":"form-control", "value" : not contact is empty  ? contact.name :'') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Phone
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("phone","class":"form-control", "value" : not contact is empty  ? contact.phone :'') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Email
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("email","class":"form-control", "value" : not contact is empty  ? contact.email :'') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Content
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            <!--<div name="div_content" id="div_content"> {{not contact is empty ? contact.content : ""}}</div>
                            {{ hidden_field("contact", "value": not contact is empty ? contact.content : "") }}-->

                            {{ text_area("content", "This is the Description","class" :"form-control", "rows": 8,
                            "value": not contact is empty ? contact.content : "" ) }}
                        </div>
                    </div>

                    <div class="form-group right">
                        <label class="control-label col-md-2">Status</label>
                        <div class="col-md-10">
                            <?php
                                // Creating a Select Tag with an empty option
                                echo $this->tag->selectStatic(
                                        array(
                                            'status',
                                            array(
                                                '1' => 'Active',
                                                '0' => 'Inactive'
                                            ),
                                            'useEmpty'      => true,
                                            'emptyText'     => 'Please, choose one...',
                                            'emptyValue'    => '',
                                            'class'         => 'form-control',
                                            'value'         => !empty($contact) ? $contact->status : '',
                                        )
                                    );
                            ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green">Save</button>
                            <button type="button" class="btn default">Cancel</button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- END FORM-->
        </div>
    </div>
    <!-- END VALIDATION STATES-->
</div>
