
<!-- BEGIN LOGO -->
<div class="logo">
    <a href="index.html">
        <img src="../assets/pages/img/logo-big.png" alt="" /> </a>
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div class="content">
    <!-- BEGIN LOGIN FORM -->
    {{ form("cpanel/" ~ ActionName,"class": "loginForm") }}
    <h3 class="form-title font-green">Sign In</h3>
    <div class="alert alert-danger display-hide">
        <button class="close" data-close="alert"></button>
        <span> Enter any username and password. </span>
    </div>
    <div class="form-group">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9">Username</label>
         {{ text_field("username",
                "id":"username",
                "autocomplete" : "off",
                "placeholder" : "Username or Email",
                "class" : "form-control form-control-solid placeholder-no-fix") }}
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Password</label>
        {{ password_field("password",
                "id":"password",
                "size":"20",
                "autocomplete" : "off",
                "placeholder" : "Password",
                "class" : "form-control form-control-solid placeholder-no-fix") }}
    </div>
    <div class="form-actions">
        <button type="submit" class="btn green uppercase">Login</button>
        <label class="rememberme check">
            <input type="checkbox" name="remember" value="1" />Remember </label>
    </div>
    </form>
    <!-- END LOGIN FORM -->
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".loginForm input").keypress(function(e){
            if(e.which == 13) {
                $("form").submit();
            }
        });
    });
</script>
