<div class="main-container contact-wrapper with-sidebar">
    <br>
    <div class="contact-fom-info">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-content contact-page">
                        <article>
                            <div class="entry-content">
                                <div class="phm_row hasteck_row phm_row-fluid">
                                    <div class="row-container">
                                        <div class="parvez_column parvez_column_container parvez_col-sm-6">
                                            <div class="parvez_wrapper">
                                                <div class="parvez_text_column parvez_content_element ">
                                                    <div class="parvez_wrapper">
                                                        <h2>Leave us a message</h2>
                                                        <div class="wpcf7">
                                                            <form action="/contact/add" method="post" class="wpcf7-form">
                                                                <div class="contact-input">
                                                                    <span class="your-name">
																		<input type="text" name="name" required="true" value="" size="40" class="wpcf7-text" placeholder="Name (required)" />
                                                                    </span>
                                                                    <span class="your-email">
																						<input type="email" name="email" required="true" value="" size="40" class="wpcf7-text wpcf7-email" placeholder="Email (required)" />
																					</span>
                                                                    <span class="your-subject">
																						<input type="text" name="phone" required="true" value="" size="40" class="wpcf7-text" placeholder="Phonenumber" />
																					</span>
                                                                </div>
                                                                <div class="contact-message">
                                                                    <span class="your-message">
																						<textarea name="message" required="true" cols="40" rows="10" class="wpcf7-textarea" placeholder="Message"></textarea>
																					</span>
                                                                </div>
                                                                <div class="contact-submit">
                                                                    <input type="submit" value="Submit Form" class="wpcf7-submit button" />
                                                                </div>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="parvez_column parvez_column_container parvez_col-sm-6">
                                            <div class="parvez_wrapper">
                                                <!-- <div class="map-wrapper">
                                                    <div id="map"></div>
                                                </div> -->
                                                <div class="parvez_text_column parvez_content_element ">
                                                    <div class="parvez_wrapper">
                                                        <h2>GIVE US A CALL</h2>
                                                        <p>Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum.</p>
                                                        <p class="phone">0987. 654. 321</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- .entry-content -->
                        </article>
                        <!-- #post -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Google Map js -->
<script type='text/javascript' src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/frontend/js/jquery.gmap.js"></script>

<script type="text/javascript">
    $('#map').gMap({
        scrollwheel: false,
        zoom: 17,
        address: "Pall Mall, London England",
        markers: [{
            address: "Pall Mall, London England",
            html: '',
            icon: {
                image: "images/fashion/style/marker.png",
                iconsize: [32, 47],
                iconanchor: [32, 47]
            },
            popup: true
        }]
    });
</script>