<div class="main-container front-page">
    <div class="page-content">
        <div class="entry-content">
            <div class="phm_row hasteck_row phm_row-fluid home-slider">
                <div class="row-container">
                    <div class="parvez_column parvez_column_container parvez_col-sm-12">
                        <div class="parvez_wrapper">
                            <div class="parvez_revslider_element parvez_content_element">
                                <div id="rev_slider_3_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#bddde5;padding:0px;margin-top:0px;margin-bottom:0px;">
                                    <!-- START REVOLUTION SLIDER -->
                                    <div id="rev_slider_3_1" class="rev_slider fullwidthabanner tp-overflow-hidden" style="display:none;">
                                        <ul>
                                            <!-- SLIDE  -->
                                            <li data-index="rs-1" data-transition="random" data-slotamount="9" data-masterspeed="600" data-saveperformance="on" data-thumb="images/accessories/slider/banner1-100x50.jpg" data-rotate="0" data-title="Slide-1" data-description="">
                                                <!-- MAIN IMAGE -->
                                                <img src="http://demo.roadthemes.com/saharan_accessories/wp-content/uploads/2015/08/banner1.jpg" alt="" width="1170" height="418" data-bgposition="right bottom" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                                                <!-- LAYERS -->

                                                <!-- LAYER NR. 1 -->
                                                <div class="tp-caption text1-1 customin lft tp-resizeme" id="slide-5-layer-1" data-x="104" data-y="114" data-width="auto" data-height="auto" data-speed="1500" data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;" data-easing="Power3.easeInOut" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="4000" style="z-index: 5; white-space: nowrap; color: rgba(255, 255, 255, 1.00);padding:0px 0px 0px 0px;border-color:rgba(255, 255, 255, 1.00);">Last chance
                                                </div>

                                                <!-- LAYER NR. 2 -->
                                                <div class="tp-caption text1-2 customin lft tp-resizeme" id="slide-5-layer-2" data-x="99" data-y="157" data-width="auto" data-height="auto" data-speed="1500" data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;" data-easing="Power3.easeInOut" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="4500" style="z-index: 6; white-space: nowrap; color: rgba(255, 255, 255, 1.00);padding:0px 0px 0px 0px;border-color:rgba(255, 255, 255, 1.00);">Bigest sale
                                                </div>

                                                <!-- LAYER NR. 3 -->
                                                <div class="tp-caption text1-3 lfb lft tp-resizeme" id="slide-5-layer-3" data-x="102" data-y="230" data-width="548" data-height="40" data-speed="1500" data-easing="Power3.easeInOut" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="5000" style="z-index: 7; min-width: 548px; max-width: 548px; max-width: 40px; max-width: 40px; white-space: normal; color: rgba(255, 255, 255, 1.00);border-color:rgba(34, 34, 34, 1.00);">Donec vitae est placerat, porttitor sem at, trum erat. Donec vitaeest placerat, porttitor sem at, rutrum erat donec vitae est placerat.
                                                </div>
                                            </li>
                                            <!-- SLIDE  -->
                                            <li data-index="rs-1" data-transition="random" data-slotamount="9" data-masterspeed="600" data-saveperformance="on" data-thumb="images/accessories/slider/banner2-100x50.jpg" data-rotate="0" data-title="Slide-2" data-description="">
                                                <!-- MAIN IMAGE -->
                                                <img src="http://demo.roadthemes.com/saharan_accessories/wp-content/uploads/2015/08/banner2.jpg" alt="" width="1171" height="418" data-bgposition="right bottom" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                                                <!-- LAYERS -->

                                                <!-- LAYER NR. 1 -->
                                                <div class="tp-caption text1-1 customin lft tp-resizeme" id="slide-6-layer-1" data-x="104" data-y="114" data-width="auto" data-height="auto" data-speed="1500" data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;" data-easing="Power3.easeInOut" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="4000" style="z-index: 5; white-space: nowrap; color: rgba(255, 255, 255, 1.00);padding:0px 0px 0px 0px;border-color:rgba(255, 255, 255, 1.00);">Last chance
                                                </div>

                                                <!-- LAYER NR. 2 -->
                                                <div class="tp-caption text1-2 customin lft tp-resizeme" id="slide-6-layer-2" data-x="99" data-y="157" data-width="auto" data-height="auto" data-speed="1500" data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;" data-easing="Power3.easeInOut" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="4500" style="z-index: 6; white-space: nowrap; color: rgba(255, 255, 255, 1.00);padding:0px 0px 0px 0px;border-color:rgba(255, 255, 255, 1.00);">Bigest sale
                                                </div>

                                                <!-- LAYER NR. 3 -->
                                                <div class="tp-caption text1-3 lfb lft tp-resizeme" id="slide-6-layer-3" data-x="102" data-y="230" data-width="548" data-height="40" data-speed="1500" data-easing="Power3.easeInOut" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="5000" style="z-index: 7; min-width: 548px; max-width: 548px; max-width: 40px; max-width: 40px; white-space: normal; color: rgba(255, 255, 255, 1.00);border-color:rgba(34, 34, 34, 1.00);">Donec vitae est placerat, porttitor sem at, trum erat. Donec vitaeest placerat, porttitor sem at, rutrum erat donec vitae est placerat.
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- END REVOLUTION SLIDER -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="phm_row hasteck_row phm_row-fluid">
                <div class="row-container">
                    <div class="parvez_column parvez_column_container parvez_col-sm-3">
                        <div class="parvez_wrapper">
                            <div class="phm_row hasteck_row parvez_inner phm_row-fluid">
                                <div class="furniture-categories parvez_column parvez_column_container parvez_col-sm-12">
                                    <div class="parvez_wrapper">
                                        <div class="parvez_wp_custommenu parvez_content_element">
                                            <div class="widget widget_nav_menu">
                                                <h2 class="widgettitle">CATEGORIES</h2>
                                                <div class="menu-categories-container">
                                                    <ul id="menu-categories" class="menu">
                                                                {%- for cate_item in root_cate_items %}
                                                                    {% set child_cate_items = cate_item.getChilds() %}
                                                                    {% if child_cate_items|length > 0 %}
                                                                        <li class="children-menu"><a href="#">{{cate_item.name}}</a>
                                                                        {%- macro print_child_cate_level(cate_level_items) %}
                                                                            {%- for child_cate_item in cate_level_items %}
                                                                                {% if loop.first %}
                                                                                    <ul class="sub-menu">
                                                                                {% endif %}
                                                                                <li class="children-menu">
                                                                                    <a href="{{ child_cate_item.seo_url }}" >
                                                                                        {{ child_cate_item.name }}
                                                                                    </a>                                                                        
                                                                                    {% set next_cate_level_items = child_cate_item.getChilds() %}
                                                                                    {% if next_cate_level_items %}
                                                                                        {{ print_child_cate_level(next_cate_level_items) }}
                                                                                    {% endif %}
                                                                                </li>
                                                                                {% if loop.last %}
                                                                                    </ul>
                                                                                {% endif %}
                                                                            {%- endfor %}
                                                                        {%- endmacro %}
                                                                        {{ print_child_cate_level(child_cate_items) }}             
                                                                    {% else %}
                                                                        <li ><a href="#">{{cate_item.name}}</a>    
                                                                    {% endif %}  
                                                                {%- endfor %}                                                        
                                                        
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                            <div class="phm_row hasteck_row parvez_inner phm_row-fluid">
                                <div class="bestseller parvez_column parvez_column_container parvez_col-sm-12">
                                    <div class="parvez_wrapper">
                                        <div class="parvez_text_column parvez_content_element ">
                                            <div class="parvez_wrapper">
                                                <h3><strong>BESTSELLER</strong></h3>
                                            </div>
                                        </div>
                                        <div class="bootexpert columns-1">
                                            <div class="shop-products row grid-view">
                                            {%- for p_item in product %}
                                                <div class="first last item-col col-xs-12 col-sm-12">
                                                    <div class="product-wrapper">
                                                        <div class="list-col4">
                                                            <div class="product-image">
                                                                <a href="" title="Aenean eu tristique">
                                                                    {% if p_item.ProductImage|length>0 %}
                                                                        <img src="{{p_item.ProductImage[0].img_url}}" class="primary_image" alt="05" />
                                                                    {% endif %}
                                                                    {% if p_item.ProductImage|length>1 %}
                                                                        <img src="{{p_item.ProductImage[1].img_url}}" class="secondary_image" alt="06" />
                                                                    {% endif %}
                                                                </a>
                                                                <div class="action clearfix">
                                                                    <div class="quickviewbtn">
                                                                        <a data-target="#productModal" data-toggle="modal" href="" class="detail-link quickview fa fa-eye" tabindex="0">Quick View</a>
                                                                    </div>
                                                                    <div class="add-cart">
                                                                        <p class="product bootexpert add_to_cart_inline">
                                                                            <a href="" class="button add_to_cart_button">Add to cart</a>
                                                                        </p>
                                                                    </div>
                                                                    <div class="add-to-links">
                                                                        <div class="yith-wcwl-add-to-wishlist">
                                                                            <div>
                                                                                <a href="" class="add_to_wishlist">Add to Wishlist</a>
                                                                            </div>
                                                                            <div class="clear"></div>

                                                                        </div>
                                                                        <div class="clear"></div>
                                                                        <div class="bootexpert product compare-button">
                                                                            <a href="" class="compare button">Compare</a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="list-col8">
                                                            <div class="gridview">
                                                                <h2 class="product-name"><a href="">{{p_item.name}}</a></h2>
                                                                <div class="ratings">
                                                                    <div class="star-rating" title="Rated 4.33 out of 5"><span class="width86"><strong class="rating">4.33</strong> out of 5</span></div>
                                                                </div>
                                                               <div class="price-box">
																					<del><span class="amount">&pound;{{p_item.original_price}}</span></del> <ins><span class="amount">&pound;{{p_item.price}}</span></ins>
																				</div>
                                                            </div>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                    </div>
                                                </div>
                                            {%- endfor %}                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="parvez_column parvez_column_container parvez_col-sm-9">
                        <div class="parvez_wrapper">
                            <div class="phm_row hasteck_row parvez_inner phm_row-fluid home-banner">
                                <div class="parvez_column parvez_column_container parvez_col-sm-12">
                                    <div class="parvez_wrapper">
                                        <div class="parvez_text_column parvez_content_element ">
                                            <div class="parvez_wrapper">
                                                <p>
                                                    <a href="#"><img class="alignnone wp-image-5692" src="http://demo.roadthemes.com/saharan_accessories/wp-content/uploads/2015/07/img_banner04.jpg" alt="img_banner03" width="870" height="194" /></a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                           {%- for cate_item in root_cate_items %}
                            {% set products = cate_item.Product %}
                            {% if products|length > 0 %}
                            <div class="phm_row hasteck_row parvez_inner phm_row-fluid products-carousel2 parvez_custom_1">
                                <div class="parvez_column parvez_column_container parvez_col-sm-12">
                                    <div class="parvez_wrapper">
                                        <div class="parvez_text_column parvez_content_element ">
                                            <div class="parvez_wrapper">
                                                <h3><span>{{cate_item.name}}</span></h3>
                                            </div>
                                        </div>
                                        <div class="bootexpert columns-4">
                                            <div id="shop-products-4-1" class="shop-products row grid-view">
                                                {%- for product_item in products %}
                                                <div class="item-col col-xs-12 col-sm-3">
                                                    <div class="product-wrapper">
                                                        <div class="list-col4">
                                                            <div class="product-image">
                                                                <a href="" title="Ornare sed consequat">
                                                                    {% if product_item.ProductImage|length>0 %}
                                                                        <img src="{{product_item.ProductImage[0].img_url}}" class="primary_image" alt="05" />
                                                                    {% endif %}
                                                                    {% if product_item.ProductImage|length>1 %}
                                                                        <img src="{{product_item.ProductImage[1].img_url}}" class="secondary_image" alt="06" />
                                                                    {% endif %}
                                                                   
                                                                </a>
                                                                <div class="action clearfix">
                                                                    <div class="quickviewbtn">
                                                                        <a data-target="#productModal" data-toggle="modal" href="" class="detail-link quickview fa fa-eye" tabindex="0">Quick View</a>
                                                                    </div>
                                                                    <div class="add-cart">
                                                                        <p class="product bootexpert add_to_cart_inline">
                                                                            <a href="" class="button add_to_cart_button">Add to cart</a>
                                                                        </p>
                                                                    </div>
                                                                    <div class="add-to-links">
                                                                        <div class="yith-wcwl-add-to-wishlist">
                                                                            <div>
                                                                                <a href="" class="add_to_wishlist">Add to Wishlist</a>
                                                                            </div>
                                                                            <div class="clear"></div>

                                                                        </div>
                                                                        <div class="clear"></div>
                                                                        <div class="bootexpert product compare-button">
                                                                            <a href="" class="compare button">Compare</a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="list-col8">
                                                            <div class="gridview">
                                                                <h2 class="product-name"><a href="">{{product_item.name}}</a></h2>
                                                                <div class="ratings">
                                                                    <div class="star-rating" title="Rated 5.00 out of 5"><span class="width100"><strong class="rating">5.00</strong> out of 5</span></div>
                                                                </div>
                                                                <div class="price-box"><span class="amount">&pound;{{product_item.price}}</span></div>

                                                            </div>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                    </div>
                                                </div>
                                                {%- endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {%- endfor %}

                            <div class="phm_row hasteck_row parvez_inner phm_row-fluid">
                                <div class="parvez_column parvez_column_container parvez_col-sm-12">
                                    <div class="parvez_wrapper">
                                        <div class="parvez_text_column parvez_content_element ">
                                            <div class="parvez_wrapper">
                                                <h3><strong>OUR BRANDS</strong></h3>
                                            </div>
                                        </div>
                                        <div id="brands-carousel-5" class="brands-carousel">
                                            {%- for brand_item in brand %}
                                            <div>
                                                <a href="/brand/{{brand_item.brand_id}}" title=""><img src="{{brand_item.logo}}" alt="{{brand_item.name}}" /></a>
                                            </div>
                                            {%- endfor %}
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="phm_row hasteck_row phm_row-fluid corporate-about parvez_custom_2">
                <div class="row-container">
                    <div class="parvez_column parvez_column_container parvez_col-sm-4 parvez_custom_3">
                        <div class="parvez_wrapper">
                            <div class="parvez_text_column parvez_content_element ">
                                <div class="parvez_wrapper">
                                    <p>FREE SHIPPING ON ORDER OVER $99</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="parvez_column parvez_column_container parvez_col-sm-4 parvez_custom_3">
                        <div class="parvez_wrapper">
                            <div class="parvez_text_column parvez_content_element ">
                                <div class="parvez_wrapper">
                                    <p>STORE ONLINE SUPPORT 24/7</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="parvez_column parvez_column_container parvez_col-sm-4 parvez_custom_4">
                        <div class="parvez_wrapper">
                            <div class="parvez_text_column parvez_content_element ">
                                <div class="parvez_wrapper">
                                    <p>30 DAYS MONEY BACK GUARANTEED !</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>