<div class="row">
    <div class="span12">
        <div class="row">
            <div class="span12" data-motopress-type="static">
                <div class="slider_off"> </div>
            </div>
        </div>
        <div class="row">
            <div class="span12" data-motopress-type="loop">
                <div id="post-203" class="post-203 page type-page status-publish hentry">
                    <div class="row ">
                        <div class="span8 ">
                            <section class="lazy-load-box effect-fade">
                                <ul class="posts-list list_1">
                                    <?php $i =0;?>
                                    {% for h in hotList.items %}
                                    
                                    <li class="row-fluid list-item-<?php echo $i; ?>">
                                        <figure class="featured-thumbnail thumbnail ">
                                            <a href="/tin-tuc/{{h.menu_id}}/{{h.getSEOCate()}}/{{h.content_id}}/{{h.getSEOTitle()}}/" title="{{h.title}}">
                                             
                                         <img src="{{h.img_url}}" alt="{{h.title}}">
                                   
                                            </a>
                                        </figure>
                                        <div class="post_content">
                                            <h2 class="post-title">
                                                <a href="/tin-tuc/{{h.menu_id}}/{{h.getSEOCate()}}/{{h.content_id}}/{{h.getSEOTitle()}}/" title="{{h.title}}">{{h.title}}</a>
                                            </h2>
                                            <span class="post_date">
                                                <time datetime="2014-10-03T18:18:10">{{ date("Y-m-d H:i", time(h.create_date)) }}</time>
                                            </span>
                                            <span class="post_comment">
                                                <a href="/tin-tuc/{{h.menu_id}}/{{h.getSEOCate()}}/{{h.content_id}}/{{h.getSEOTitle()}}/" class="comments_link">{{h.total_view}} Views</a>
                                            </span>
                                        </div>
                                    </li>
                                    <?php $i++ ?>
                                     {% endfor %}
                                    
                                   
                                </ul>
                            </section>
                            <div class="clear"></div>
                            <div class="spacer"></div>
                            <div class="row ">
                                <div class="span5 ">
                                    <section class="lazy-load-box effect-fade" >
                                        <h2>Tin tức mới</h2>
                                        <ul class="recent-posts list_2 unstyled">
                                             {% for n in newsList.items %}
                                            <li class="recent-posts_li">
                                                <figure class="thumbnail featured-thumbnail">
                                                    <a href="/tin-tuc/{{n.menu_id}}/{{n.getSEOCate()}}/{{n.content_id}}/{{n.getSEOTitle()}}/" title="{{n.title}}">
                                                        <img width="143" height="101" src="{{n.img_url}}" alt="{{n.title}}">
                                                    </a>
                                                </figure>
                                                <div class="inner">
                                                    <h5>
                                                        <a href="/tin-tuc/{{n.menu_id}}/{{n.getSEOCate()}}/{{n.content_id}}/{{n.getSEOTitle()}}/" title="{{n.title}}">                                                              {{n.title}}
                                                        </a>
                                                    </h5>
                                                    <div class="excerpt">
                                                        <a href="/tin-tuc/{{n.menu_id}}/{{n.getSEOCate()}}/{{n.content_id}}/{{n.getSEOTitle()}}/" >
                                                            {{n.description}} 
                                                        </a>
                                                    </div>
                                                    <span class="meta">
                                                        <span class="post-date">{{ date("Y-m-d H:i", time(n.create_date)) }}</span>
                                                        <span class="post-comments">
                                                            {{n.total_view}}
                                                        </span>
                                                    </span>
                                                </div>
                                                <div class="clear"></div>
                                            
                                            </li>
                                             {% endfor %}
                                        </ul>
                                    </section>
                                    <section class="lazy-load-box effect-fade" >
                                        <a href="/tin-tuc" title="Tất cả" class="btn btn-primary btn-normal btn-inline " target="_self">Tất cả</a>
                                    </section>
                                </div>
                                <div class="span3 ">
                                     <h2>Dịch vụ</h2>
                                     {% for r in serviceList.items %}
                                        <section class="lazy-load-box effect-fade" >
                                            <div class="banner-wrap ">
                                                <figure class="featured-thumbnail">
                                                    <a href="/dich-vu/{{r.menu_id}}/{{r.getSEOCate()}}/" title="{{r.title}}">
                                                        <img src="{{r.img_url}}" title="{{r.title}}" alt="{{r.title}}">
                                                    </a>
                                                </figure>
                                                <p>{{r.title}}</p>
                                            </div>
                                        </section>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="span4 ">
                            <section class="lazy-load-box effect-fade" >
                                <h2>Video nổi bật</h2>
                            </section>
                            <section class="lazy-load-box effect-fade" >
                                <ul class="recent-posts list_3 unstyled">
                                    
                                      {% for v in videoList.items %}
                                    <li class="recent-posts_li format-video clearfix">
                                        <figure class="thumbnail featured-thumbnail">
                                            <a href="/video/{{v.menu_id}}/{{v.getSEOCate()}}/{{v.content_id}}/{{v.getSEOTitle()}}/" title="{{v.title}}"><img src="{{v.img_url}}" alt="{{v.title}}"></a>
                                        </figure>
                                        <div class="inner">
                                            <span class="post_category">
                                                <a href="/video/{{v.menu_id}}/{{v.getSEOCate()}}/{{v.content_id}}/{{v.getSEOTitle()}}/" title="{{v.title}}">{{v.title}}</a>
                                            </span>
                                            <h5><a href="/video/{{v.menu_id}}/{{v.getSEOCate()}}/{{v.content_id}}/{{v.getSEOTitle()}}/" title="{{v.description}}">{{v.description}}</a></h5>
                                            <div class="excerpt">
                                                <a href="/video/{{v.menu_id}}/{{v.getSEOCate()}}/{{v.content_id}}/{{v.getSEOTitle()}}/" title="{{v.description}}"> 
                                                    {{v.description}}
                                                </a>
                                            </div>
                                            <span class="meta">
                                                <span class="post-date">{{ date("Y-m-d H:i", time(v.create_date)) }}</span>
                                                <span class="post-comments">
                                                    {{v.total_view}}
                                                </span>
                                            </span>
                                        </div>
                                        <div class="clear"></div>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </section>
                           
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>