<div class="row">
    <div class="span12" >
        <div class="row">
            <div class="span12" >
                <div class="slider_off"> </div>
            </div>
        </div>
        <div class="row">
            <div class="span12" >
                <div id="post-203" class="post-203 page type-page status-publish hentry">
                    <div class="row">
                        <div class="span12">
                            <section class="title-section">
                                <h1 class="title-header">
                                    {{content.title}}
                                </h1>
                                <ul class="breadcrumb breadcrumb__t">
                                    <li><a href="/">Trang chủ</a></li>
                                    <li class="divider"></li>
                                    <li class="active">{{content.Menu.name}}</li>
                                </ul>
                            </section>
                        </div>
                    </div>
                    <div id="content" class="row">
                        <div class="span8">
                           <p>
                            <strong>
                                {{content.description}}
                            </strong>
                           </p>
                            {{content.content}}
                        </div>
                         <div class="span4" id="sidebar">
                                <h3>Tin nổi bật</h3>
                                <ul class="post-list unstyled">
                                    {% for l in listOther.items %}
                                        <li class="cat_post_item-1 clearfix">
                                            <figure class="featured-thumbnail thumbnail">
                                                <a href="/tin-tuc/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/">
                                                    <img src="{{l.img_url}}" width="370" height="159" alt="{{l.title}}">
                                                </a>
                                            </figure>
                                            <time datetime="2011-07-15T11:31">{{ date("Y-m-d H:i", time(l.create_date)) }}</time>
                                            <span class="post-list_comment">Lượt xem: {{ l.total_view }}</span>
                                            <h4 class="post-list_h">
                                                <a class="post-title" href="/tin-tuc/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/"  title="{{l.title}}">{{l.title}}</a>
                                            </h4>
                                            <div class="excerpt">
                                                {{l.description}}
                                            </div>
                                            <a href="/tin-tuc/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/" class="btn btn-primary link">Chi tiết</a>
                                        </li>
                                    {% endfor %}
                                </ul>                           
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
