<div class="row">
    <div class="span12" >
        <div class="row">
            <div class="span12" data-motopress-type="static">
                <div class="slider_off"> </div>
            </div>
        </div>
        <div class="row">
            <div class="span12" data-motopress-type="loop">
                <div >
                    <div class="row ">
                        <div class="span8 ">
                            <div class="row ">

                                <section class="lazy-load-box effect-fade">
                                    <h2> {{title}}</h2>
                                    <ul class="recent-posts list_2 unstyled">
                                         {% for r in contentList.items %}
                                             <li>
                                                <figure class="thumbnail featured-thumbnail">
                                                    <a href="/tin-tuc/{{r.menu_id}}/{{r.getSEOCate()}}/{{r.content_id}}/{{r.getSEOTitle()}}/" title="{{r.title}}">
                                                        <img width="143" height="101" src="{{r.img_url}}" alt="{{r.title}}"></a>
                                                </figure>
                                                <div class="inner">
                                                    <h5>
                                                        <a href="/tin-tuc/{{r.menu_id}}/{{r.getSEOCate()}}/{{r.content_id}}/{{r.getSEOTitle()}}/" title="{{r.title}}">
                                                            {{r.title}}
                                                        </a>
                                                    </h5>
                                                    <div class="excerpt">
                                                        <a href="/tin-tuc/{{r.menu_id}}/{{r.getSEOCate()}}/{{r.content_id}}/{{r.getSEOTitle()}}/" title="{{r.title}}">
                                                            {{r.description}}
                                                        </a>
                                                    </div>
                                                    <span class="meta">
                                                        <span class="post-date">{{ date("Y-m-d H:i", time(r.create_date)) }}</span>
                                                        <span class="post-comments">
                                                            <a href="#">{{ r.total_view }}</a>
                                                        </span>
                                                    </span>
                                                </div>
                                                <div class="clear"></div>
                                            </li>
                                        {% endfor %}                                     
                                    </ul>
                                </section>
                                 {% if contentList.total_pages>1 %}
                                <div class="pagination pagination__posts">
                                    <ul>
                                        <?php for($i = 0 ; $i < $contentList->total_pages; $i++): ?>
                                            <li class={{current == i +1 ? "active" :"" }}>
                                                <a href="{{ seoUrl}}{{ i+1}}/" >{{i +1 }}</a>
                                            </li>
                                        <?php endfor; ?>
                                    </ul>
                                </div>
                                 {% endif %}   
                            </div>
                        </div>
                        <div class="span4" id="sidebar">
                                <h3>Tin nổi bật</h3>
                                <ul class="post-list unstyled">
                                    {% for l in listOther.items %}
                                        <li class="cat_post_item-1 clearfix">
                                            <figure class="featured-thumbnail thumbnail">
                                                <a href="/tin-tuc/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/">
                                                    <img src="{{l.img_url}}" width="370" height="159" alt="{{l.title}}">
                                                </a>
                                            </figure>
                                            <time datetime="2011-07-15T11:31">{{ date("Y-m-d H:i", time(l.create_date)) }}</time>
                                            <span class="post-list_comment">Lượt xem: {{ l.total_view }}</span>
                                            <h4 class="post-list_h">
                                                <a class="post-title" href="/tin-tuc/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/"  title="{{l.title}}">{{l.title}}</a>
                                            </h4>
                                            <div class="excerpt">
                                                {{l.description}}
                                            </div>
                                            <a href="/tin-tuc/{{l.menu_id}}/{{l.getSEOCate()}}/{{l.content_id}}/{{l.getSEOTitle()}}/" class="btn btn-primary link">Chi tiết</a>
                                        </li>
                                    {% endfor %}
                                </ul>                           
                        </div>
                    </div>
                    <div class="clear"></div>

                </div>
            </div>
        </div>
    </div>
</div>
</div>
