<div class="footer-top">
                    <div class="container">
                        <div class="footer-top-inner">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="widget widget_contact_us">
                                        <h3 class="widget-title">Contact Us</h3>
                                        <ul>
                                            <li>Mon-Sun: 10:30am-6:30pm</li>
                                            <li>Phone: (657) 227-8539</li>
                                            <li>Email: itvhs9200@gmail.com</li>
                                        </ul>
                                    </div>
                                    <div class="widget widget_social">
                                        <ul class="social-icons">
                                            <li><a class="facebook social-icon" href="https://www.facebook.com/" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                            <li><a class="twitter social-icon" href="https://twitter.com/" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                            <li><a class="tumblr social-icon" href="https://www.tumblr.com/" title="Tumblr" target="_blank"><i class="fa fa-tumblr"></i></a></li>
                                            <li><a class="google-plus social-icon" href="https://plus.google.com/" title="Google-plus" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                                            <li><a class="dribbble social-icon" href="https://dribbble.com/" title="Dribbble" target="_blank"><i class="fa fa-dribbble"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="widget widget_menu">
                                        <h3 class="widget-title">Top Menu</h3>
                                        <div class="menu-top-menu-container">
                                            <ul id="menu-top-menu-1" class="nav_menu">
                                                <li class="first"><a href="#">My Account</a></li>
                                                <li><a href="#">My Wishlist</a></li>
                                                <li><a href="#">Shopping Cart</a></li>
                                                <li class="last"><a href="#">Checkout</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="widget widget_menu">
                                        <h3 class="widget-title">Customer care</h3>
                                        <div class="menu-customer-care-container">
                                            <ul class="nav_menu">
                                                <li class="first"><a href="#">Sitemap</a></li>
                                                <li><a href="#">Term &#038; Conditions</a></li>
                                                <li><a href="#">Gift Vouchers</a></li>
                                                <li class="last"><a href="#">BestSellers</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="widget widget_wysija">
                                        <h2 class="widgettitle">Newsletter</h2>
                                        <div class="widget_wysija_cont">
                                            <form id="form-newsletter1" method="post" action="#wysija" class="widget_wysija">
                                                <p class="wysija-paragraph">
                                                    <input type="text" name="email" class="wysija-input" title="Email" placeholder="Email" value="" />
                                                </p>
                                                <input class="wysija-submit wysija-submit-field" type="submit" value="Subscribe!" />
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-bottom">
                    <div class="container">
                        <div class="footer-bottom-inner">
                            <div class="copyright-info">
                                Copyright © 2015 <a href="/">itvhomeshopping.com</a> All Rights Reserved
                            </div>
                            <div class="bottom-right">
                            </div>
                        </div>
                    </div>
                </div>