
                <div class="top-bar">
                    <div class="container">
                        <div class="top-bar-inner clearfix">
                            <div class="phone-number">
                                HOTLINE: <span>(657) 227-8539</span>
                            </div>
                            <div class="top-menu widget">
                                <div class="menu-top-menu-container">
                                    <ul id="menu-top-menu" class="nav_menu">
                                        <li class="first"><a href="">My Account</a></li>
                                        <li><a href="#">My Wishlist</a></li>
                                        <li><a href="#">Shopping Cart</a></li>
                                        <li><a href="#">Checkout</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header">
                    <div class="container">
                        <div class="header-inner">
                            <div class="row">
                                <div class="col-xs-12 col-md-3">
                                    <div class="logo">
                                        <a href="/" title="Saharan Accessories" rel="home">
                                            <img src="/frontend/images/Logo_itv_homeshopping.png" alt="" />
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-md-9">                                    
                                    <div class="header-search">
                                        <div class="widget bootexpert widget_product_search">

                                            <form method="get" id="searchform" action="/product/search">
                                                <input type="text" value="" name="key" id="ws" placeholder="Search product..." />
                                                <button id="wsearchsubmit" class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="nav-container">
                        <div class="container">
                            <div class="nav-inner clearfix">
                                <div class="horizontal-menu">
                                    <div class="visible-large">
                                        <div id="saharan_mega_main_menu" class="dropdowns_trigger-hover dropdowns_animation-anim_5">
                                            <div class="menu_holder">
                                                <div class="mmm_fullwidth_container"></div>
                                                <!-- class="fullwidth_container" -->
                                                <nav class="menu_inner">
                                                    <!-- /class="nav_logo" -->
                                                    <ul>
                                                        <li class="active-menu-item first default_dropdown drop_to_right">
                                                            <a href="/" class="item_link">
                                                                <span class="link_content">
																		<span class="link_text">Home</span>
                                                                </span>
                                                            </a>
                                                        </li>
                                                        
                                                        {%- macro print_cate_level(cate_level_items) %}
                                                                {%- for cate_item in cate_level_items %}
                                                                    {% if loop.first %}
                                                                         <ul class="mega_dropdown">
                                                                    {% endif %}
                                                                    <li class="default_dropdown drop_to_right children-menu" >
                                                                        <a href="/product/{{cate_item.cate_id}}/date/{{cate_item.getSEOName()}}/1" class="item_link">
                                                                            <span class="link_content">
                                                                                    <span class="link_text">{{ cate_item.name }}</span>
                                                                            </span>
                                                                        </a>                                                                        
                                                                        {% set next_cate_level_items = cate_item.getChilds() %}
                                                                        {% if next_cate_level_items %}
                                                                            {{ print_cate_level(next_cate_level_items) }}
                                                                        {% endif %}
                                                                    </li>
                                                                    {% if loop.last %}
                                                                        </ul>
                                                                    {% endif %}
                                                                {%- endfor %}
                                                            {%- endmacro %}
                                                                                                           
                                                        
                                                        {%- for cate_item in root_cate_items %} {% set child_cate_items = cate_item.getChilds() %} {% if child_cate_items|length > 0 %}
                                                        <li class="multicolumn_dropdown drop_to_right children-menu"><a class="item_link" href="/product/{{cate_item.cate_id}}/date/{{cate_item.getSEOName()}}/1">
                                                            <span class="link_content">
																		<span class="link_text">{{cate_item.name}}
                                                                </span>
                                                            </span></a> 

                                                            {{ print_cate_level(child_cate_items) }} {% else %}
                                                        <li class="default_dropdown drop_to_right children-menu"><a class="item_link" href="/product/{{cate_item.cate_id}}/date/{{cate_item.getSEOName()}}/1"> <span class="link_content"><span class="link_text">{{cate_item.name}}</span></span></a> {% endif %} {%- endfor %}                                                        
                                                    </ul>
                                                </nav>
                                                <!-- /class="menu_inner" -->
                                            </div>
                                            <!-- /class="menu_holder" -->
                                        </div>
                                        <!-- /id="saharan_mega_main_menu" -->
                                    </div>
                                    <!-- Mobile Menu -->
                                    <div class="visible-small mobile-menu">
                                        <div class="nav-container">
                                            <div class="mbmenu-toggler">Menu<span class="mbmenu-icon"></span></div>
                                            <nav class="mobile-menu-container">
                                                <ul id="menu-horizontal-menu" class="nav-menu">
                                                    <li class="first"><a href="/">Home</a>                                                       
                                                    </li>
                                                    <li class="children-menu"><a href="/product">Products</a>
                                                        {%- macro mobile_print_cate_level(cate_level_items) %}
                                                                {%- for cate_item in cate_level_items %}
                                                                    {% if loop.first %}
                                                                         <ul class="sub-menu">
                                                                    {% endif %}
                                                                    <li>
                                                                        <a href="/product/{{cate_item.cate_id}}/date/{{cate_item.getSEOName()}}/1" >
                                                                           {{ cate_item.name }}
                                                                        </a>                                                                        
                                                                        {% set next_cate_level_items = cate_item.getChilds() %}
                                                                        {% if next_cate_level_items %}
                                                                            {{ mobile_print_cate_level(next_cate_level_items) }}
                                                                        {% endif %}
                                                                    </li>
                                                                    {% if loop.last %}
                                                                        </ul>
                                                                    {% endif %}
                                                                {%- endfor %}
                                                            {%- endmacro %}
                                                            {{ mobile_print_cate_level(root_cate_items) }}        
                                                            <!-- /.mega_dropdown -->
                                                    </li>                                                    
                                                    <li><a href="/about">About Us</a></li>
                                                    <li><a href="/contact">Contact</a></li>
                                                </ul>
                                            </nav>
                                        </div>
                                    </div>
                                    <!-- Mobile Menu -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- .header -->
                <div class="clearfix"></div>