<div id="secondary" class="col-xs-12 col-md-3 sidebar-category">
    <aside id="woocommerce_product_categories-6" class="widget bootexpert widget_product_categories">
        <h3 class="widget-title"><span>Categories</span></h3>
        <div class="widget_content">
            <ul class="product-categories">
                {%- for cate_item in childCate %}
                <li class="cat-item cat-item-47 cat-parent">
                    <a href="/product/{{cate_item.cate_id}}/date/{{cate_item.getSEOName()}}/1">{{cate_item.name}}</a>
                    <span class="count">({{cate_item.Product|length + cate_item.Products|length}})</span>
                </li>
                {%- endfor %}
            </ul>
        </div>
    </aside>
     <aside id="woocommerce_product_categories-6" class="widget bootexpert widget_product_categories">
        <h3 class="widget-title"><span>Brand</span></h3>
        <div class="widget_content">
            <ul class="product-categories">
                {%- for brand_item in brandList %}
                <li class="cat-item cat-item-47 cat-parent">
                    <a href="/brand/{{brand_item.brand_id}}/{{brand_item.getSEOName()}}/1/date">{{brand_item.name}}</a>
                    <span class="count">({{brand_item.Product|length}})</span>
                </li>
                {%- endfor %}
            </ul>
        </div>
    </aside>
    <!-- <aside id="text-10" class="widget widget_text">
        <div class="widget_content">
            <div class="textwidget">
                <a href="#"><img src="http://demo.roadthemes.com/saharan_accessories/wp-content/uploads/2015/08/banner_right.jpg " alt=""></a>
            </div>
        </div>
    </aside> -->
</div>

<div id="archive-product" class="col-xs-12 col-md-9">
    <div class="toolbar">
        <div class="view-mode">
            <a href="#" class="grid  active" title="Grid"><i class="fa fa-th-large"></i><span>Grid</span></a>
            <a href="#" class="list " title="List"><i class="fa fa-th-list"></i><span>List</span></a>
        </div>
        {% if productList.total_pages|length >1 %}
        <p class="bootexpert-result-count">
            Showing 1–10 of {{productList.total_pages}} results</p>
        {% endif %}
        <form class="bootexpert-ordering hidden-xs" method="get">
            <div class="orderby-wrapper">
                <label>Sort By</label>
                <select name="orderby" id="orderby" class="orderby" style="display: none;">      
                    <option value="date">Sort by newness</option>
                    <option value="price">Sort by price: low to high</option>
                    <option value="price-desc">Sort by price: high to low</option>
                </select>
            </div>
        </form>
        <div class="clearfix"></div>
    </div>

    <div class="archive-border shop-sidebar left-sidebar">
       
        <div class="bootexpert shop-products row grid-view">
            {%- for pd_item in productList.items %}
            <div class="item-col col-xs-12 col-sm-4">
                <div class="product-wrapper">
                    {% if pd_item.price >0 %}
                    <span class="onsale"><span class="sale-text">Sale</span></span>
                    {% endif %}
                    <div class="list-col4 ">
                        <div class="product-image">
                            <!-- <a href="/product/{{pd_item.cate_id}}/{{pd_item.getSEOCate()}}/{{pd_item.product_id}}/{{pd_item.getSEOTitle()}}" title="{{pd_item.name}}">
                                                    {% if pd_item.ProductImage|length>0 %}
                                                        <img width="400" height="400" src="{{pd_item.ProductImage[0].img_url}}" class="primary_image" alt="05" />
                                                    {% endif %}
                                                    {% if pd_item.ProductImage|length>1 %}
                                                        <img width="400" height="400" src="{{pd_item.ProductImage[1].img_url}}" class="secondary_image" alt="06" />
                                                    {% endif %}
                                                    
                            </a> -->
                            {% if pd_item.ProductImage|length>0 %}
                                                                <a href="/product/{{pd_item.cate_id}}/{{pd_item.getSEOCate()}}/{{pd_item.product_id}}/{{pd_item.getSEOTitle()}}" title="{{pd_item.name}}" style="background-image: url('{{pd_item.ProductImage[0].img_url}}')" class="primary-image">
                                                                </a>
                                                                {% endif %}
                                                    {% if pd_item.ProductImage|length>1 %}
                                                                    <a href="/product/{{pd_item.cate_id}}/{{pd_item.getSEOCate()}}/{{pd_item.product_id}}/{{pd_item.getSEOTitle()}}" title="{{pd_item.name}}" style="background-image: url('{{pd_item.ProductImage[1].img_url}}')" class="secondary-image">
                                                                    </a>
                                                                {% endif %}
                           
                        </div>
                    </div>
                    <div class="list-col8 ">
                        <div class="gridview">
                            <h2 class="product-name">
                                                    <a href="/product/{{pd_item.cate_id}}/{{pd_item.getSEOCate()}}/{{pd_item.product_id}}/{{pd_item.getSEOTitle()}}">                                                           {{pd_item.name}}
                                                    </a>
                                                </h2>
                           
                            <div class="price-box">
                                {% if pd_item.price >0 %}
                                <del><span class="amount">£{{pd_item.original_price}}</span></del>
                                <ins><span class="amount">£{{pd_item.price}}</span></ins> {% else %}
                                <span class="amount">£{{pd_item.price}}</span> {% endif %}
                            </div>

                        </div>
                        <div class="listview">
                            <h2 class="product-name">
                                                    <a href="/product/{{pd_item.cate_id}}/{{pd_item.getSEOCate()}}/{{pd_item.product_id}}/{{pd_item.getSEOTitle()}}">                                                           {{pd_item.name}}
                                                    </a>
                                                </h2>
                          
                            <div class="price-box">
                                {% if pd_item.price >0 %}
                                <del><span class="amount">£{{pd_item.original_price}}</span></del>
                                <ins><span class="amount">£{{pd_item.price}}</span></ins> {% else %}
                                <span class="amount">£{{pd_item.price}}</span> {% endif %}
                            </div>
                            <div class="product-desc">
                                {{pd_item.short_description}}
                            </div>
                           
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            {%- endfor %}
        </div>
        {% if productList.total_pages >1 %}
        <div class="toolbar tb-bottom">
            <nav class="bootexpert-pagination">
                <ul class='page-numbers'>
                    {% for i in 1..productList.total_pages %}
                         {% if curentPage == i %}
                            <li><span class='page-numbers current'>{{i}}</span></li>
                        {% else %}
                            {% if type == 1 %}
                                <li><a class="page-numbers" href="/product/{{i}}/{{order}}">{{i}}</a></li>
                            {% endif %}
                            {% if type == 2 %}
                                <li><a class="page-numbers" href="/product/{{category.cate_id}}/date/{{category.getSEOName()}}/{{i}}">{{i}}</a></li>
                            {% endif %}
                            {% if type == 3 %}
                                <li><a class="page-numbers" href="/brand/{{brand.brand_id}}/{{brand.getSEOName()}}/{{i}}/{{order}}">{{i}}</a></li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}               
                </ul>
            </nav>
            <div class="clearfix"></div>
        </div>
      
        {% endif %}
    </div>
</div>

<script>
        $('#orderby').on('change', function (e) {
            var optionSelected = $("option:selected", this);
            var valueSelected = this.value;
            {% if type == 2 %}
                var link = '/product/{{category.cate_id}}/'+ valueSelected +'/{{category.getSEOName()}}/1' ;
                window.location.href = link;
            {% endif %}
            {% if type == 1 %}
                var link = '/product/1/'+ valueSelected ;
                window.location.href = link;
            {% endif %}
            {% if type == 3 %}
                var link = '/brand/{{brand.brand_id}}/{{brand.getSEOName()}}/1/'+ valueSelected ;
                window.location.href = link;
            {% endif %}
          
        });
        $('#orderby').val('{{order}}')
        $('#orderby').trigger('chosen:updated');
    </script>