<div class="span12">
    <div class="page_content">
        <div class="clear"></div>
    </div>
    <ul id="portfolio-grid" class="filterable-portfolio thumbnails portfolio-3cols isotope" data-cols="3cols" style="visibility: visible; position: relative; overflow: hidden; height: 1265px;">
        <script>
            jQuery(document).ready(function($) {
                var $container = $('#portfolio-grid'),
                    items_count = $(".portfolio_item").size();

                $(window).load(function() {
                    var selector = window.location.hash.replace(/^#category/, '.term');

                    if (selector == "#") {
                        selector = '';
                    }

                    setColumnWidth();
                    $container.isotope({
                        itemSelector: '.portfolio_item',
                        hiddenClass: 'portfolio_hidden',
                        resizable: false,
                        transformsEnabled: true,
                        layoutMode: 'fitRows',
                        filter: selector
                    })

                    $('#filters .active').removeClass('active')
                    $('#filters li a[data-filter="' + selector + '"]').parent('li').addClass('active');
                    change_hash(selector)
                });

                function getNumColumns() {
                    var $folioWrapper = $('#portfolio-grid').data('cols');

                    if ($folioWrapper == '2cols') {
                        var winWidth = $("#portfolio-grid").width(),
                            column = 2;
                        if (winWidth < 380) column = 1;
                        return column;
                    } else if ($folioWrapper == '3cols') {
                        var winWidth = $("#portfolio-grid").width(),
                            column = 3;
                        if (winWidth < 380) column = 1;
                        else if (winWidth >= 380 && winWidth < 788) column = 2;
                        else if (winWidth >= 788 && winWidth < 1160) column = 3;
                        else if (winWidth >= 1160) column = 3;
                        return column;
                    } else if ($folioWrapper == '4cols') {
                        var winWidth = $("#portfolio-grid").width(),
                            column = 4;
                        if (winWidth < 380) column = 1;
                        else if (winWidth >= 380 && winWidth < 788) column = 2;
                        else if (winWidth >= 788 && winWidth < 1160) column = 3;
                        else if (winWidth >= 1160) column = 4;
                        return column;
                    }
                }

                function setColumnWidth() {
                    var columns = getNumColumns(),
                        containerWidth = $("#portfolio-grid").width(),
                        postWidth = containerWidth / columns;
                    postWidth = Math.floor(postWidth);

                    $(".portfolio_item").each(function(index) {
                        $(this).css({
                            "width": postWidth + "px"
                        });
                    });
                }

                function arrange() {
                    setColumnWidth();
                    $container.isotope('reLayout');
                }

                $(window).on("debouncedresize", function(event) {
                    arrange();
                });

                // Filter projects
                $('.filter a').click(function() {
                    var $this = $(this).parent('li');
                    // don't proceed if already active
                    if ($this.hasClass('active')) {
                        return;
                    }


                    var $optionSet = $this.parents('.filter');
                    // change active class
                    $optionSet.find('.active').removeClass('active');
                    $this.addClass('active');

                    var selector = $(this).attr('data-filter');
                    $container.isotope({
                        filter: selector
                    });
                    change_hash(selector)

                    var hiddenItems = 0,
                        showenItems = 0;
                    $(".portfolio_item").each(function() {
                        if ($(this).hasClass('portfolio_hidden')) {
                            hiddenItems++;
                        };
                    });

                    showenItems = items_count - hiddenItems;
                    if (($(this).attr('data-count')) > showenItems) {
                        $(".pagination__posts").css({
                            "display": "block"
                        });
                    } else {
                        $(".pagination__posts").css({
                            "display": "none"
                        });
                    }
                    return false;
                });

                function change_hash(hash) {
                    hash = hash.replace(/^.term/, 'category');
                    window.location.href = '#' + hash;

                    $('.pagination a').each(function() {
                        var item = $(this),
                            href = item.attr('href'),
                            end_slice = href.indexOf('#') == -1 ? href.length : href.indexOf('#');

                        href = href.slice(0, end_slice);
                        item.attr({
                            'href': href + '#' + hash
                        })
                    })
                }
            });
        </script>
        {% for r in videoList.items %}
        <li class="portfolio_item  ">
            <div class="portfolio_item_holder">
                <figure class="thumbnail thumbnail__portfolio">
                    <a href="/video/{{r.menu_id}}/{{r.getSEOCate()}}/{{r.content_id}}/{{r.getSEOTitle()}}/" class="image-wrap" title="{{r.title}}" rel="prettyPhoto">
                        <img width="390" src="{{r.img_url}}" alt="{{r.title}}">
                        <span class="zoom-icon"></span>
                    </a>
                </figure>
                <div class="caption caption__portfolio">
                    <h3><a href="/video/{{r.menu_id}}/{{r.getSEOCate()}}/{{r.content_id}}/{{r.getSEOTitle()}}/">{{r.title}}</a></h3>
                    <p class="excerpt">{{r.description}} </p>
                    <p><a href="/video/{{r.menu_id}}/{{r.getSEOCate()}}/{{r.content_id}}/{{r.getSEOTitle()}}/" class="btn btn-primary">Chi tiết</a></p>

                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% if videoList.total_pages>1 %}
    <div class="pagination pagination__posts">
        <ul>
            <?php for($i = 0 ; $i < $videoList->total_pages; $i++): ?>
                <li class={{current==i +1 ? "active" : "" }}>
                    <a href="{{ seoUrl}}{{ i+1}}/">{{i +1 }}</a>
                </li>
                <?php endfor; ?>
        </ul>
    </div>
    {% endif %}
</div>