<div class="main-container">
    <div class="page-content">
        <div class="product-page">
            <div class="container">
                <nav class="bootexpert-breadcrumb">
                    <a href="/">Home</a>
                    <span class="separator">&gt;</span>
                    <a href="/product">Products</a>
                    <span class="separator">&gt;</span>
                    <a href="/product/{{product.Category.cate_id}}/{{product.Category.getSEOName()}}/1">{{product.Category.name}}</a>
                    <span class="separator">&gt;</span>{{product.name}}
                </nav>
            </div>
            <div class="product-view">
                <div class="product">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-md-9">
                                <div class="single-product-image">
                                    <div class="images single-images gallery">
                                        {%- for image in product.ProductImage %}
                                        <a href="{{image.img_url}}" class="bootexpert-main-image zoom" data-gal="prettyPhoto[gallery1]">
                                            <img src="{{image.img_url}}" class="attachment-shop_single"/>
                                        </a>
                                        {%- endfor %}
                                    </div>
                                    <div class="thumbnails single-thumbnails columns-3">
                                        {%- for image in product.ProductImage %}
                                         <div>
                                            <img src="{{image.img_url}}"  />
                                        </div>
                                        {%- endfor %}
                                    </div>
                                </div>
                                <div class="summary entry-summary single-product-info">
                                    <h2 class="product_title entry-title">{{product.name}}</h2>
                                    <div class="bootexpert-product-rating">
                                        <div class="star-rating" title="Rated 4.00 out of 5">
                                            <span class="width80">
                                                <strong class="rating">4.00</strong> out of <span>5</span> based on 
                                                <span class="rating">1</span> customer rating</span>
                                        </div>
                                    </div>
                                    <div class="short-description">
                                        <p>
                                        {{product.short_description}}
                                        </p>
                                    </div>
                                    <div class="price-box">
                                        <p class="price">
                                            <del><span class="amount">&pound;80.00</span></del>
                                            <ins><span class="amount">&pound;70.00</span></ins>
                                        </p>
                                    </div>
                                    <form class="cart" method="post" enctype='multipart/form-data'>
                                        
                                        <div class="quantity">
                                            <input type="number" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" />
                                        </div>
                                        <button type="submit" class="single_add_to_cart_button button alt">Add to cart</button>
                                    </form>
                                   
                                </div>
                                <!-- .summary -->
                            </div>
                            <div class="col-xs-12 col-md-3">
                                <div class="widget related_products_widget">
                                    <h3 class="widget-title"><span>Related</span></h3>
                                    <div class="related products">
                                        <div class="shop-products row grid-view">
                                            {%- for related_item in productRelated %}
                                            <div class="first last item-col col-xs-12 col-sm-12">
                                                <div class="product-wrapper">
                                                    <div class="list-col4">
                                                        <div class="product-image">
                                                            <a href="/product/{{product.cate_id}}/{{product.getSEOCate()}}/{{product.product_id}}/{{product.getSEOTitle()}}">                                                               
                                                                {% if related_item.ProductImage|length>0 %}
                                                                    <img  src="{{related_item.ProductImage[0].img_url}}" class="primary_image"  />
                                                                {% endif %}
                                                                {% if related_item.ProductImage|length>1 %}
                                                                    <img src="{{related_item.ProductImage[1].img_url}}" class="secondary_image"  />
                                                                {% endif %}
                                                                
                                                            </a>
                                                        </div>
                                                    </div>
                                                    <div class="list-col8">
                                                        <div class="gridview">
                                                            <h2 class="product-name"><a href="/product/{{product.cate_id}}/{{product.getSEOCate()}}/{{product.product_id}}/{{product.getSEOTitle()}}">{{related_item.name}}</a></h2>
                                                            <div class="ratings">
                                                                <div class="star-rating" title="Rated 5.00 out of 5">
                                                                    <span class="width100"><strong class="rating">5.00</strong> out of 5</span>
                                                                </div>
                                                            </div>
                                                            <div class="price-box">
                                                                <span class="amount">&pound;55.00</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                            {%- endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="bootexpert-tabs wc-tabs-wrapper">
                                <ul class="tabs parveztabs">
                                    <li rel="tab-description" class="tab active"><a>Description</a></li>
                                   
                                </ul>
                                <div class="panel active" id="tab-description">
                                    <p>
                                    {{product.description}}
                                    </p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- #product-2249 -->
            </div>
        </div>
    </div>
</div>