<div class="main-container">
    <div class="page-content">
        <div class="product-page">
            <div class="container">
                <nav class="bootexpert-breadcrumb">
                    <a href="/">Home</a>
                    <span class="separator">&gt;</span>
                    <a href="/product">Products</a>
                    <span class="separator">&gt;</span>
                    <a href="/product/{{product.Category.cate_id}}/date/{{product.Category.getSEOName()}}/1">{{product.Category.name}}</a>
                    <span class="separator">&gt;</span>{{product.name}}
                </nav>
            </div>
            <div class="product-view">
                <div class="product">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-md-9">
                                <div class="single-product-image">
                                    <div class="images single-images gallery">
                                        {%- for image in product.ProductImage %}
                                        <a href="{{image.img_url}}" class="bootexpert-main-image zoom" data-gal="prettyPhoto[gallery1]">
                                            <img src="{{image.img_url}}" class="attachment-shop_single"/>
                                        </a>
                                        {%- endfor %}
                                    </div>
                                    <div class="thumbnails single-thumbnails columns-3">
                                        {%- for image in product.ProductImage %}
                                         <div>
                                            <img src="{{image.img_url}}"  />
                                        </div>
                                        {%- endfor %}
                                    </div>
                                </div>
                                <div class="summary entry-summary single-product-info">
                                    <h2 class="product_title entry-title">{{product.name}}</h2>

                                    <table class="table">
                                        <tr>
                                            <th width="40%">Size</th>
                                            <th>Price</th>
                                        </tr>
                                        <tr>
                                            <td>
                                            <span class="product-size">{{product.size}}</span>
                                            </td>
                                            <td>
                                            <div class="price-box">
                                                <span class="price">
                                                    {% if product.price >0 %}
                                                    <ins><span class="amount">${{product.price}}</span></ins> 
                                                    <del><span class="amount">${{product.original_price}}</span></del>
                                                    {% else %}
                                                    <span class="amount">${{product.original_price}}</span>
                                                    {% endif %}
                                                </span>
                                            </td>
                                        </tr>
                                    </table>

                                    <!-- <div class="price-block">                                   
                                    <div class="short-description">
                                        <b>Size: </b>{{product.size}}
                                    </div>
                                    <div class="price-box">
                                        <p class="price">
                                            {% if product.price >0 %}
                                                <ins><span class="amount">${{product.price}}</span></ins> 
                                                <del><span class="amount">${{product.original_price}}</span></del>
                                            {% else %}
                                                <span class="amount">${{product.original_price}}</span>
                                            {% endif %}
                                        </p>
                                    </div>
                                    </div> -->
                                    <p>
                                    {{product.description}}
                                    </p>
                                </div>
                                <!-- .summary -->
                            </div>
                            <div class="col-xs-12 col-md-3">
                                {% if productRelated|length > 0 %}
                                <div class="widget related_products_widget">
                                    <h3 class="widget-title"><span>Related</span></h3>
                                    <div class="related products">
                                        <div class="shop-products row grid-view">
                                            {%- for related_item in productRelated %}
                                            <div class="first last item-col col-xs-12 col-sm-12">
                                                <div class="product-wrapper">
                                                    <div class="list-col4">
                                                        <div class="product-image">
                                                            <a href="/product/{{product.cate_id}}/{{related_item.getSEOCate()}}/{{related_item.product_id}}/{{related_item.getSEOTitle()}}">                                                               
                                                                {% if related_item.ProductImage|length>0 %}
                                                                    <img  src="{{related_item.ProductImage[0].img_url}}" class="primary_image"  />
                                                                {% endif %}
                                                                {% if related_item.ProductImage|length>1 %}
                                                                    <img src="{{related_item.ProductImage[1].img_url}}" class="secondary_image"  />
                                                                {% endif %}
                                                                
                                                            </a>
                                                        </div>
                                                    </div>
                                                    <div class="list-col8">
                                                        <div class="gridview">
                                                            <h2 class="product-name"><a href="/product/{{product.cate_id}}/{{related_item.getSEOCate()}}/{{related_item.product_id}}/{{related_item.getSEOTitle()}}">{{related_item.name}}</a></h2> 
                                                            
                                                           <div class="price-box">
                                                                <p class="price">
                                                                     {% if related_item.price >0 %}
                                                                        <del><span class="amount">${{related_item.original_price}}</span></del>
                                                                        <ins><span class="amount">${{related_item.price}}</span></ins> {% else %}
                                                                        <span class="amount">${{related_item.original_price}}</span> 
                                                                    {% endif %}
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                            {%- endfor %}
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                            <!-- <div class="bootexpert-tabs wc-tabs-wrapper">
                                <ul class="tabs parveztabs">
                                    <li rel="tab-description" class="tab active"><a>Description</a></li>
                                   
                                </ul>
                                <div class="panel active" id="tab-description">
                                    <p>
                                    {{product.description}}
                                    </p>
                                </div>
                            </div> -->

                        </div>
                    </div>
                </div>
                <!-- #product-2249 -->
            </div>
        </div>
    </div>
</div>