<div class="main-container front-page">
    <div class="page-content">
        <div class="shop_content">
            <br>
            <div class="container">
                <nav class="bootexpert-breadcrumb">
                    <a href="/">Home</a>
                    <span class="separator">&gt;</span> {{category.name}}
                </nav>
                <div class="row">
                     {{ partial('productList') }}
                </div>
            </div>
        </div>
    </div>
</div>