<div class="row">
    <div class="span12" >
        <div class="row">
            <div class="span12">
                <div class="slider_off"> </div>
            </div>
        </div>
        <div class="row">
            <div class="span12" >
                <div id="post-203" class="post-203 page type-page status-publish hentry">
                    <div class="row">
                        <div class="span12">
                            <section class="title-section">
                                <h1 class="title-header">
                                    Thông tin liên hệ 
                                </h1>
                                <ul class="breadcrumb breadcrumb__t">
                                    <li><a href="#">Trang chủ</a></li>
                                    <li class="divider"></li>
                                    <li class="active">Liên hệ</li>
                                </ul>
                            </section>
                        </div>
                    </div>
                    <div id="content" class="row">
                        <div class="span12" >
                            <div id="post-14" class="post-14 page type-page status-publish hentry">
                                <div class="row ">
                                    <div class="span12 ">
                                        <div class="google-map">
                                            <iframe src="https://maps.google.com/maps?hl=en&q=92 Thích Quảng Đức, Hồ Chí Minh, Việt Nan&ie=UTF8&z=16&iwloc=A&output=embed" frameborder="0" width="100%" height="300" marginwidth="0" marginheight="0" scrolling="no">
                                            </iframe>
                                        </div>
                                    </div>
                                    <div class="span4 ">
                                        <h2>Thông tin liên hệ</h2>
                                        <h5>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</h5>
                                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque la udantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia.
                                            <br>
                                        </p>
                                        <address>
                                          <strong>The Company Name Inc.<br>
                                          9870 St Vincent Place,<br>
                                          Glasgow, DC 45 Fr 45.</strong><br>
                                          Telephone: +1 800 603 6035<br>
                                          FAX: +1 800 889 9898<br>
                                          E-mail: <a href="mailto:info@demolink.org">mail@demolink.org</a><br>
                                        </address>
                                    </div>
                                    <div class="span8 ">
                                        <h2>Liên hệ</h2>
                                        <div class="wpcf7" id="wpcf7-f208-p14-o1">
                                            <div class="screen-reader-response"></div>
                                            <form action="lienhe/contact" method="post" class="wpcf7-form" novalidate="novalidate">
                                                <div class="row-fluid">
                                                    <p class="span4 field">
                                                        <span class="wpcf7-form-control-wrap your-name">
                                                            <input type="text" name="name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" placeholder="Name:">
                                                        </span> 
                                                    </p>
                                                    <p class="span4 field">
                                                        <span class="wpcf7-form-control-wrap your-email"
                                                              ><input type="email" name="email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" placeholder="E-mail:">
                                                        </span> 
                                                    </p>
                                                    <p class="span4 field">
                                                        <span class="wpcf7-form-control-wrap your-phone">
                                                            <input type="text" name="phone" value="" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false" placeholder="Phone:">
                                                        </span>
                                                    </p>
                                                </div>
                                                <p class="field">
                                                    <span class="wpcf7-form-control-wrap your-message">
                                                        <textarea name="content" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false" placeholder="Message:"></textarea>
                                                    </span> 
                                                </p>
                                                <p class="submit-wrap">
                                                    <input type="reset" value="Xóa" class="btn btn-primary">
                                                    <input type="submit" value="Gửi" class="wpcf7-form-control wpcf7-submit btn btn-primary">
                                                    <img class="ajax-loader" src="/frontend/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;">
                                                    <div class="ajax-loader"></div>
                                                </p>
                                                <div class="wpcf7-response-output wpcf7-display-none"></div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>