<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Saharan Accessories - 1 | HTML Template</title>
    <meta name="description" content="Rubbez HTML Ecommerce Template">
    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Custom Google Web Font -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&#038;subset=latin,latin-ext" rel="stylesheet" type="text/css" media="all" />
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,700,900" rel="stylesheet" type="text/css" media="all" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

<!--     {{ assets.outputCss('css') }}-->
   
<!--    -->
    <!-- END CORE PLUGINS -->
    
    <!-- Libs CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="/frontend/lib/slick/slick-theme.css">
    <!-- REVOLUTION STYLE SHEETS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/rs-plugin/css/settings.css" />

    <!-- jquery Chosen Style -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/chosen/chosen.min.css">
    <!-- Style Switcher CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/styleswitch/styleswitcher.css">
    <!-- Style NTM CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/ntm/collapse.css">

    <!-- Bootstrap and Other CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/css/cache.skin.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/language-selector.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/bootexpert.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/megamenu_style.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/icomoon.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/bootexpert-compose.css">

    <!-- Theme Style -->
    <link rel="stylesheet" type="text/css" href="/frontend/css/style.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/accessories/theme1.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/accessories/accessories.css">
    
    <!-- Modernizr -->
    <script src="/frontend/js/vendor/modernizr-2.8.3.min.js"></script>
    <!--[if lt IE 9]>
		  <script src="js/html5shiv.min.js"></script>
		  <script src="js/respond.min.js"></script>
		<![endif]-->
</head>

<body>
    <div class="wrapper ">
        <div class="page-wrapper">
            <div class="header-container accessories">
                {{ partial('header') }}
            </div>
            {{ content() }}
            <div class="footer accessories">
                {{ partial('footer') }}
            </div>
        </div>
        <!-- .page -->
    </div>
    <!-- .wrapper -->
    <!-- BACK TO TOP -->
    <div id="back-top" class="hidden-xs hidden-sm hidden-md"></div>
    <!-- QUICKVIEW PRODUCT -->
    <div class="quickview-wrapper" id="quickview-wrapper">
        <!-- Modal -->
        <div class="modal fade" id="productModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="modal-product">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true" class="closeqv"><i class="fa fa-times"></i></span>
                            </button>
                            <div id="quickview-content">
                                <div class="bootexpert product">
                                    <div class="product-images">
                                        <div class="main-image images">
                                            <img alt="9_3" src="images/accessories/product/9_3.jpg">
                                        </div>
                                        <div class="quick-thumbnails">
                                            <div class="slick-slide">
                                                <a href="images/accessories/product/9_3.jpg">
                                                    <img alt="9_3" class="attachment-shop_thumbnail" src="images/accessories/product/9_3-185x185.jpg">
                                                </a>
                                            </div>
                                            <div class="slick-slide">
                                                <a class="zoom first" href="images/accessories/product/5_6.jpg">
                                                    <img alt="5_6" class="attachment-shop_thumbnail" src="images/accessories/product/5_6-185x185.jpg">
                                                </a>
                                            </div>
                                            <div class="slick-slide">
                                                <a class="zoom" href="images/accessories/product/4_5.jpg">
                                                    <img alt="4_5" class="attachment-shop_thumbnail" src="images/accessories/product/4_5-185x185.jpg">
                                                </a>
                                            </div>
                                            <div class="slick-slide">
                                                <a class="zoom" href="images/accessories/product/3_6.jpg">
                                                    <img alt="image1xxl" class="attachment-shop_thumbnail" src="images/accessories/product/3_6-185x185.jpg">
                                                </a>
                                            </div>
                                            <div class="slick-slide">
                                                <a class="zoom" href="images/accessories/product/8_4.jpg">
                                                    <img alt="image1xxl" class="attachment-shop_thumbnail" src="images/accessories/product/8_4-185x185.jpg">
                                                </a>
                                            </div>
                                            <div class="slick-slide">
                                                <a class="zoom" href="images/accessories/product/7_3.jpg">
                                                    <img alt="image1xxl" class="attachment-shop_thumbnail" src="images/accessories/product/7_3-185x185.jpg">
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-info">
                                        <h2>Condimentum posuere</h2>
                                        <div class="price-box">
                                            <p class="price">
                                                <span class="special-price">
														<span class="amount">$100.00</span>
                                                </span>
                                                <span class="old-price">
														<span class="amount">$105.00</span>
                                                </span>
                                            </p>
                                        </div>
                                        <a href="" class="see-all">See all features</a>
                                        <div class="quick-add-to-cart">
                                            <form method="post" class="cart">
                                                <div class="single_variation_wrap">
                                                    <div class="variations_button">
                                                        <div class="quantity">
                                                            <input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity">
                                                        </div>
                                                        <button class="single_add_to_cart_button button alt" type="submit">Add to cart</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="quick-desc">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus
                                        </div>
                                        <div class="social-sharing">
                                            <div class="widget widget_socialsharing_widget">
                                                <h3 class="widget-title">Share this product</h3>
                                                <ul class="social-icons">
                                                    <li>
                                                        <a class="facebook social-icon" href="https://www.facebook.com/" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                                                    </li>
                                                    <li>
                                                        <a class="twitter social-icon" href="https://twitter.com/" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                                                    </li>
                                                    <li>
                                                        <a class="pinterest social-icon" target="_blank" title="Pinterest" href="#"><i class="fa fa-pinterest"></i></a>
                                                    </li>
                                                    <li>
                                                        <a class="gplus social-icon" href="https://plus.google.com/" title="Google-plus" target="_blank"><i class="fa fa-google-plus"></i></a>
                                                    </li>
                                                    <li>
                                                        <a class="linkedin social-icon" href="https://linkedin.com/" title="Dribbble" target="_blank"><i class="fa fa-linkedin"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- .product-images -->
                        </div>
                        <!-- .modal-product -->
                    </div>
                    <!-- .modal-body -->
                </div>
                <!-- .modal-content -->
            </div>
            <!-- .modal-dialog -->
        </div>
        <!-- END Modal -->
    </div>
    <!-- END QUICKVIEW PRODUCT -->
  {{ assets.outputJs('js') }}

<!-- Google Map js -->
		<script type='text/javascript' src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript" src="/frontend/js/jquery.gmap.js"></script>

    <script type="text/javascript">
			$('#map').gMap({
				scrollwheel: false,
				zoom: 17,
				address: "Pall Mall, London England",
				markers: [{
					address: "Pall Mall, London England",
					html: '',
					icon: {
						image: "images/fashion/style/marker.png",
						iconsize: [32, 47],
						iconanchor: [32, 47]
					},
					popup: true
				}]
			});
		</script>
    <script type="text/javascript">
        jQuery(document).ready(function () {            
            $(function () {
                var url = location.pathname;
                var aUrl = url.split('/')[1];
                
                if (aUrl == '') {
                    $('.menu_inner li').removeClass('active-menu-item');
                    $('.menu_inner li:first').addClass('active-menu-item');
                } else {
                    $('.menu_inner li').removeClass('active-menu-item');
                    $('.menu_inner li a[href="/' + aUrl + '"]').parent().addClass('active-menu-item');
                    
                }
            });
        })
    </script>

</body>

</html>