<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Saharan Accessories - 1 | HTML Template</title>
    <meta name="description" content="Rubbez HTML Ecommerce Template">
    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Custom Google Web Font -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&#038;subset=latin,latin-ext" rel="stylesheet" type="text/css" media="all" />
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,700,900" rel="stylesheet" type="text/css" media="all" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

<!--     {{ assets.outputCss('css') }}-->
   
<!--    -->
    <!-- END CORE PLUGINS -->
    
    <!-- Libs CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="/frontend/lib/slick/slick-theme.css">
    <!-- REVOLUTION STYLE SHEETS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/rs-plugin/css/settings.css" />

    <!-- jquery Chosen Style -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/chosen/chosen.min.css">
    <!-- Style Switcher CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/styleswitch/styleswitcher.css">
    <!-- Style NTM CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/lib/ntm/collapse.css">

    <!-- Bootstrap and Other CSS -->
    <link rel="stylesheet" type="text/css" href="/frontend/css/cache.skin.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/language-selector.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/bootexpert.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/megamenu_style.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/icomoon.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/bootexpert-compose.css">

    <!-- Theme Style -->
    <link rel="stylesheet" type="text/css" href="/frontend/css/style.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/accessories/theme1.css">
    <link rel="stylesheet" type="text/css" href="/frontend/css/accessories/accessories.css">
    
    <!-- Modernizr -->
    <script src="/frontend/js/vendor/modernizr-2.8.3.min.js"></script>
    <!--[if lt IE 9]>
		  <script src="js/html5shiv.min.js"></script>
		  <script src="js/respond.min.js"></script>
		<![endif]-->
    {{ assets.outputJs('js-header') }}
</head>

<body>
    <div class="wrapper ">
        <div class="page-wrapper">
            <div class="header-container accessories">
                {{ partial('header') }}
            </div>
            {{ content() }}
            <div class="footer accessories">
                {{ partial('footer') }}
            </div>
        </div>
        <!-- .page -->
    </div>
    <!-- .wrapper -->
    <!-- BACK TO TOP -->
    <div id="back-top" class="hidden-xs hidden-sm hidden-md"></div>
    
  {{ assets.outputJs('js') }}


    <script type="text/javascript">
        jQuery(document).ready(function () {            
            $(function () {
                var url = location.pathname;
                var aUrl = url.split('/')[1];
                
                if (aUrl == '') {
                    $('.menu_inner li').removeClass('active-menu-item');
                    $('.menu_inner li:first').addClass('active-menu-item');
                } else {
                    $('.menu_inner li').removeClass('active-menu-item');
                    $('.menu_inner li a[href="/' + aUrl + '"]').parent().addClass('active-menu-item');
                    
                }
            });
        })
    </script>
    

</body>

</html>