<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<html>

<head>
     {{tag.getTitle()}}
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    {{ assets.outputCss('css-mandatory') }}
    <!-- END GLOBAL MANDATORY STYLES -->

    <!-- BEGIN PAGE LEVEL PLUGINS -->
    {{ assets.outputCss('css-page-level') }}
    <!-- END PAGE LEVEL PLUGINS -->

    <!-- BEGIN THEME GLOBAL STYLES -->
    {{ assets.outputCss('css-theme-global') }}
    <!-- END THEME GLOBAL STYLES -->

    <!-- BEGIN THEME LAYOUT STYLES -->
    {{ assets.outputCss('css-theme-layout') }}
    <!-- END THEME LAYOUT STYLES -->

    {{ assets.outputJs('js-core') }}
    <!-- END CORE PLUGINS -->
</head>

<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
    <!-- BEGIN HEADER -->
    {{ partial('Header') }}
    <!-- END HEADER -->

    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar-wrapper">
            <!-- BEGIN SIDEBAR -->
            {{ partial('Sidebar') }}
            <!-- END SIDEBAR -->
        </div>
        <!-- END SIDEBAR -->

        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <!-- BEGIN CONTENT BODY -->
            <div class="page-content">
                <!-- BEGIN PAGE HEADER-->
                <!-- BEGIN THEME PANEL -->
                <!-- END THEME PANEL -->
                {{ content() }}
            </div>
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->

        <!-- BEGIN QUICK SIDEBAR -->
        <!-- END QUICK SIDEBAR -->
    </div>
     <!-- BEGIN Message Notification -->
    <div class="hidden" id="divMessage">
         {{ flashSession.output() }}
    </div>
     <!-- END Message Notification -->
    <!-- END CONTAINER -->

    <!-- BEGIN FOOTER -->
    {{ partial('Footer') }}
    <!-- END FOOTER -->

    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <!--[if lt IE 9]>
    {{ assets.outputJs('js-ie9') }}
    <![endif]-->

    <!-- BEGIN PAGE LEVEL PLUGINS -->
    {{ assets.outputJs('js-page-level-plugins') }}
    <!-- END PAGE LEVEL PLUGINS -->

    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    {{ assets.outputJs('js-theme-global') }}
    <!-- END THEME GLOBAL SCRIPTS -->

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    {{ assets.outputJs('js-page-level-scripts') }}
    <!-- END PAGE LEVEL SCRIPTS -->

    <!-- BEGIN THEME LAYOUT SCRIPTS -->
    {{ assets.outputJs('js-theme-layout') }}
    <!-- END THEME LAYOUT SCRIPTS -->
    <!-- END JAVASCRIPTS -->
</body>

</html>
