<!-- apps/views/menu/edit.phtml-->
<?php
use Multiple\Backend\Models\Category as Cate;
use Phalcon\Tag as Tag;
?>
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{base_url}}/cpanel/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{base_url}}/cpanel/{{ControllerName}}">Category manager</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            {{id > 0 ?"Edit": "Add new" }} Category
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> Menu
    <small>{{id > 0 ? "Edit" : "Add new" }} Category</small>
</h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div>
    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light bordered">
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <form action="/cpanel/{{ControllerName}}/{{ActionName}}/{{id >0 ? id :""}}" class="form-horizontal" method="post" >
                {{ hidden_field("cate_id", "value": id) }}
                <div class="form-body">
                    <div class="form-group">
                        <label class="control-label col-md-3">Name
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-4">
                            {{ text_field("name","class":"form-control","data-required":"1" , "value" : not detail is empty  ? detail.name :'') }}
                        </div>
                    </div>
                    {% if id > 0 %}
                    <div class="form-group">
                        <label class="control-label col-md-3">Seo URL
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-4">
                            {{ text_field("seo_url","class":"form-control", "value" : not detail is empty  ? detail.seo_url :'') }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <label class="control-label col-md-3">Sort order</label>
                        <div class="col-md-4">
                            {{ text_field("order_id","class":"form-control" , "value" : not detail is empty  ? detail.order_id :'') }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Parent</label>
                        <div class="col-md-4">

                            <?php
                            // Creating a Select Tag with an empty option
                            echo $this->tag->select(
                                array(
                                    'parent_id',
                                    Cate::find("parent_id = 0 and cate_id != {$id}"),
                                    'using'         => array('cate_id', 'name'),
                                    'useEmpty'      => true,
                                    'emptyText'     => '-- None --',
                                    'emptyValue'    => '0',
                                    'class'         => 'form-control',
                                    'value'         =>  !empty($detail->Cate) ? $detail->Cate->cate_id : ''
                                ));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Status</label>
                        <div class="col-md-4">
                            <?php
                            // Creating a Select Tag with an empty option
                            echo $this->tag->selectStatic(
                                array(
                                    'status',
                                    array(
                                        '1' => 'Active',
                                        '0' => 'Inactive'
                                    ),
                                    'useEmpty'      => true,
                                    'emptyText'     => 'Please, choose one...',
                                    'emptyValue'    => '',
                                    'class'         => 'form-control',
                                    'value'         => !empty($detail) ? $detail->status : '',
                                )
                            );
                            ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green">Save</button>
                            <button type="button" class="btn default">Cancel</button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- END FORM-->
        </div>
    </div>
    <!-- END VALIDATION STATES-->
</div>
