<!-- apps/views/product/edit.phtml-->
<?php
use Multiple\Backend\Models\Category as Cate;
use Multiple\Backend\Models\Brand as Brand;
?>
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{base_url}}/cpanel/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{base_url}}/cpanel/{{ControllerName}}">Product manager</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            {{id > 0 ?"Edit": "Add new" }} Product
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> Users
    <small>{{  id > 0 ? "Edit" : "Add new" }} Product </small>
</h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div>
    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light bordered" >
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <form action="/cpanel/{{ControllerName}}/{{ActionName}}{{id >0 ? '/'~id :""}}" class="form-horizontal" method="post" >
                {{ hidden_field("product_id", "value": id) }}
                <div class="form-actions top right">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green">Save</button>
                            <button type="button" class="btn default">Cancel</button>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="form-group">
                        <label class="control-label col-md-2">Name
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("name","class":"form-control","data-required":"1" , "value" : not detail is empty  ? detail.name :'') }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Category
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                             {{ hidden_field("cate_parent_id", "id" : "cate_parent_id", "value": not  detail is empty and not detail.Cate is empty ? detail.Cate.parent_id : 0 ) }}
                            <?php
                            // Creating a Select Tag with an empty option
                            echo $this->tag->select(
                                array(
                                    'cate_id',
                                    Cate::find(),
                                    'using'         => array('cate_id', 'name'),
                                    'useEmpty'      => true,
                                    'emptyText'     => 'Please, choose one...',
                                    'emptyValue'    => '',
                                    'class'         => 'form-control',
                                    'value'         => !empty($detail) ? $detail->cate_id : '',
                                    'onchange'      => "ajaxGetParentId(this); "
                                ));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Brand
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            <?php
                            // Creating a Select Tag with an empty option
                            echo $this->tag->select(
                                array(
                                    'brand_id',
                                    Brand::find(),
                                    'using'         => array('brand_id', 'name'),
                                    'useEmpty'      => true,
                                    'emptyText'     => 'Please, choose one...',
                                    'emptyValue'    => '',
                                    'class'         => 'form-control',
                                    'value'         => !empty($detail) ? $detail->brand_id : '',
                                ));
                            ?>
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Product Code
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("code","class":"form-control","data-required":"1" , "value" : not detail is empty  ? detail.code :'') }}
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="control-label col-md-2">weight
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("weight","class":"form-control Number","data-required":"1" , "value" : not detail is empty  ? detail.weight :'0.0') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Original price
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("original_price","class":"form-control Number","data-required":"1" , "value" : not detail is empty  ? detail.original_price :'0.0') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Price
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("price","class":"form-control Number","data-required":"1" , "value" : not detail is empty  ? detail.price :'0.0') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Model number
                        </label>
                        <div class="col-md-10">
                            {{ text_field("model_number","class":"form-control Number","data-required":"1" , "value" : not detail is empty  ? detail.model_number :'') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Benefit
                        </label>
                        <div class="col-md-10">
                            {{ text_field("benefit","class":"form-control Number","data-required":"1" , "value" : not detail is empty  ? detail.benefit :'') }}
                        </div>
                    </div>
                     <div class="form-group">
                        <label class="control-label col-md-2">Keyword
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_field("keyword","class":"form-control Number","data-required":"1" , "value" : not detail is empty  ? detail.keyword :'') }}
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="control-label col-md-2">Size
                        </label>
                        <div class="col-md-10">
                            {{ text_field("size","class":"form-control Number","data-required":"1" , "value" : not detail is empty  ? detail.size :'') }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Short description
                        </label>
                        <div class="col-md-10">
                            {{ text_area("short_description", "This is the Short description","class" :"form-control", "rows": 8,
                            "value": not detail is empty ? detail.short_description : "" ) }}

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Description
                            <!--<span class="required"> * </span>-->
                        </label>
                        <div class="col-md-10">
                            <div name="div_description" id="div_description"> {{not detail is empty ? detail.description : ""}}</div>
                            {{ hidden_field("description", "value": not detail is empty ? detail.description : "") }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Shipping return
                            <span class="required"> * </span>
                        </label>
                        <div class="col-md-10">
                            {{ text_area("shipping_return", "This is the Description","class" :"form-control", "rows": 8,
                            "value": not detail is empty ? detail.shipping_return : "" ) }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Status</label>
                        <div class="col-md-10">
                            <?php
                                // Creating a Select Tag with an empty option
                                echo $this->tag->selectStatic(
                                        array(
                                            'status',
                                            array(
                                                '1' => 'Active',
                                                '0' => 'Inactive'
                                            ),
                                            'class'         => 'form-control',
                                            'value'         => !empty($user) ? $user->status : '',
                                        )
                                    );
                            ?>
                        </div>
                    </div>
                    <!-- multiupload Imgage -->
                     <div class="form-group">
                        <label class="control-label col-md-2">Product Images </label>
                        <div class="col-md-10">
                            {% for img in obj['images'] %}
                                {% if not img.img_url is empty%}
                                    {{image(baseImageURL ~ img.img_url, "alt": img.name,"style" :"width:120px; height:120px;")}}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">
                        </label>
                        <div class="col-md-10">
                            <div id="uploadAvatar" class="dropzone dropzone-file-area dz-clickable">
                                <h3 class="sbold">Drop files here or click to upload</h3>
                                <p> This is just a demo dropzone. Selected files are not actually uploaded. </p>
                            </div>
                        </div>
                            {%- macro split_to_array(images, slag) %}
                                {% set lstImg = "" %}
                                {% for img in images %}
                                    {% set lstImg = lstImg ~ img.img_url  ~ (not loop.last ? slag : "")  %}
                                {% endfor %}
                                {% return lstImg %}
                            {%- endmacro %}

                            {% set lstImage = split_to_array("images" : obj['images'], "slag": slag) %}
                          {{ hidden_field("himages_old", "value": lstImage) }}
                          {{ hidden_field("himages", "value":"") }}
                    </div>
                </div>
                <div class="form-actions right">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green">Save</button>
                            <button type="button" class="btn default">Cancel</button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- END FORM-->

        </div>
    </div>
    <!-- END VALIDATION STATES-->
</div>
<script type="text/javascript">
    $(document).ready(function() {
        Dropzone.autoDiscover = false;
        $('div#uploadAvatar').dropzone({
            url:'/cpanel/{{ControllerName}}/uploadImage',
            paramName: 'favatar',
            maxFileSize: 20,
            maxFiles: 50,
            init: function() {
                this.on("maxfilesexceeded", function(file){
                   // toastr.error("Cannot upload more than 1 file!");
                });
                this.on("removedfile", function(file){
                    console.log(file);
                });
                this.on("addedfile", function(file) {
                    var removeButton = Dropzone.createElement("<a href='javascript:;'' class='btn red btn-sm btn-block'>Remove</a>");
                    var _this = this;
                    removeButton.addEventListener("click", function(e) {
                        e.preventDefault();
                        e.stopPropagation();
                        _this.removeFile(file);
                    });
                    file.previewElement.appendChild(removeButton);
                });
                this.on("success", function(file, response) {
                    response =  jQuery.parseJSON(response);
                    var _path = $.trim(response.path);
                    $("#himages_old").val('');
                    if(_path != ""){
                       $("#himages").val($("#himages").val() + "{{slag}}" + _path);
                    }
                });
            },
        });

        handleSummernote();
        $( "form" ).submit(function( event ) {
            var sHTML = $('#div_description').code(); // get code
            $('#description').val(sHTML);
            $('#description').attr('value',sHTML);
            return;
        });
    });

     function handleSummernote  () {
        $('#div_description').summernote({height: 300});
    }

    function ajaxGetParentId(_obj){
        var _id = $(_obj).find(":selected").val();
        $.ajax({
            type: "POST",
            url: "/cpanel/{{ControllerName}}/getParentCate",
            dataType: 'json',
            data: {
                id: _id
            },
            success: function(response) {
                if (response) {
                    if (response.result * 1 == 1) {
                        $("#cate_parent_id").val(response.data);
                    } else {
                        alert(response.message);
                    }
                }
            },
            error: function(error) {
                console.log(error);
            }
        });
    }
</script>
